shellcheck nit fixes

diff --git a/.config/bash/functions_generic b/.config/bash/functions_generic
--- a/.config/bash/functions_generic
+++ b/.config/bash/functions_generic
@@ -6,6 +6,7 @@ function ?()
     echo "$@" | bc -l
 }
 
+# shellcheck disable=SC2211
 function d?()
 {
     printf "%.2f\n" "$(echo "$@" | bc -l)"
@@ -46,7 +47,10 @@ function passgen()
 {
     len=${1:-30}
     domain="${2:-[[:print:]]}"
-    strings < /dev/urandom \
+    # can't do `strings /dev/urandom` because apparently strings on mac os X sucks
+    # shellcheck disable=SC2002
+    cat /dev/urandom \
+        | strings \
         | grep -o "${domain}" \
         | head -n"${len}" \
         | tr -d '\n'
@@ -56,6 +60,7 @@ function passgen()
 # Stolen from ~meyering
 function date()
 {
+    # shellcheck disable=SC2015
     {
         test $# = 0 \
             && command date +"%a %Y-%m-%d %T %z"
@@ -193,7 +198,8 @@ function down()
         pdirs="${1:-1}"
         shift
         if [ -z "${OLDPWD}" ]; then
-            printf "Cannot go down on \$OLDPWD: not set!\n" >&2
+            # shellcheck disable=SC2016
+            printf 'Cannot go down on $OLDPWD: not set!\n' >&2
             return
         fi
         current_pwd="$(pwd)"
@@ -250,6 +256,7 @@ function setup-ssh-key-login()
         ssh-keygen -t ed25519 -f "${keyfile}"
         ssh-copy-id -i "${keyfile}" "${desthost}"
     else
-        printf "Undefined:\n$desthost=%s\n\$keyfile=%s\n" "${desthost}" "${keyfile}"
+        # shellcheck disable=SC2016
+        printf 'Undefined:\n$desthost=%s\n$keyfile=%s\n' "${desthost}" "${keyfile}"
     fi
 }
