run shellcheck on all shell code; fix most errors and warnings

diff --git a/.config/bash/scm_prompt_setup b/.config/bash/scm_prompt_setup
--- a/.config/bash/scm_prompt_setup
+++ b/.config/bash/scm_prompt_setup
@@ -11,22 +11,27 @@ function ensure_source_present ()
         curl $REMOTE_URL | sed -e 's/^__git_ps1 ()$/_dotfiles_scm_info ()/g' > "${GIT_PROMPT}"
 }
 
-function scmmode () {
-    if [ $# -eq 1 ] && [ $1 == 'off' ]; then
-        function _dotfiles_scm_info () { echo -n; }
-    elif [ $# -eq 0 ] || ([ $# -eq 1 ] && [ "${1}" == 'on' ]); then
+# shellcheck disable=SC2120
+function scmmode ()
+{
+    if [ $# -eq 1 ] && [ "${1}" == 'off' ]; then
+        function _dotfiles_scm_info () { printf ""; }
+    elif [ $# -eq 0 ] || { [ $# -eq 1 ] && [ "${1}" == 'on' ]; }; then
         if [ -f "$BASH_MOD_DIR/source_control/git-prompt" ]; then
+            # shellcheck disable=SC2034
             GIT_PS1_SHOWDIRTYSTATE=1
+            # shellcheck disable=SC2034
             GIT_PS1_SHOWSTASHSTATE=1
+            # shellcheck disable=SC2034
             GIT_PS1_SHOWUPSTREAM="auto"
             source "$BASH_MOD_DIR/source_control/git-prompt"
         elif [ -f "$BASH_MOD_DIR/source_control/scm-prompt" ]; then
             source "$BASH_MOD_DIR/source_control/scm-prompt"
         else
-            echo "ERROR: file $BASH_MOD_DIR/source_control/*-prompt NOT FOUND"
+            printf "ERROR: file %s/source_control/*-prompt NOT FOUND\n" "${BASH_MOD_DIR}" >&2
         fi
     else
-        echo "Usage: scmmode [on|off]"
+        printf "Usage: scmmode [on|off]\n" >&2
     fi
 }
 
